FROM centos

RUN yum install -y java-11-openjdk
VOLUME /tmp
ADD target/PruebaJenkins.jar app.jar

RUN sh -c 'touch /app.jar'
EXPOSE 7070
ENTRYPOINT ["java","-Djava.sercurity.egd=file:/dev/./urandom","-jar","/app.jar"]